version: 2.1

jobs:
  execute_playbook:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9c:0c:9f:2b:0a:3a:e7:d1:83:b8:00:ab:0d:cc:f4:2a"                

workflows:
  my_workflow:
    jobs:
      - execute_playbook
